### ISSUE TITLE
Compatibility with latest release of Sketch app.

### ISSUE THREAD

**Issue by mikeprecious** [margusholland/Comma#10]
Hi there, thanks for your work on this plugin. Wondered if you had plans to update the plugin to work with the latest release of Sketch app. 

Really like the keyboard commands for Sentence Case and Title Case. These two functions still lack in the native Sketch app command lineup. 

Thanks!

**Comment by margusholland** [comment]
I’m on 40.3 as the current official release and it’s working for me. What issues are you having?

**Comment by mikeprecious** [comment]
Reinstall of the plugin, computer reboot, and restarting everything appears to have been the solution here. Aforementioned commands now work. Thanks for touching base on this. Kind regards
