### ISSUE TITLE
not compatible with 3.4 (?)

### ISSUE THREAD

**Issue by gitdistill** [margusholland/Comma#3]

**Comment by margusholland** [comment]
It was written under 3.4, so should work fine with it.

**Comment by gitdistill** [comment]
weird, neither the menu item or the key command works for me. I see the top level menu name selected, looks like the sketch app window then loses focus but nothing happens.

Tried both selecting the text inside the text layer, as well as just selecting the layer. Both inside a group and outside.

osx 10.9.5, app store version.

**Comment by margusholland** [comment]
I have no tested is under 10.9, so this could potentially be an issue. Can you open Console and see if something is written into the log when you try to run the commands?

**Comment by margusholland** [comment]
Selecting only the text inside a layer is not intended to work anyway, it only works for complete layers. I just tested it under the 3.4 App Store version and don’t seem have any issues.

**Comment by margusholland** [comment]
I’ve seen this "Sketch window loses focus", but this seems to be a bug in Sketch itself, because restarting Sketch fixes it. Can you confirm whether this fixes it for you?

**Comment by gitdistill** [comment]
I had tried restarting, but it looks like with the new version of sketch its working now!

Thanks anyhow!
