### ISSUE TITLE
not working in version 3.2.4

### ISSUE THREAD

**Issue by layeredges** [margusholland/Comma#4]
its in not working in version 3.2.4

**Comment by margusholland** [comment]
Can you be more specific, what is not working in 3.2.4? I just tried it with 3.2.4 and cannot see any issues. Can you check console.app and see if anything is written into logs by Sketch?

**Comment by layeredges** [comment]
When I tried to apply the upper case nothing happen

**Comment by margusholland** [comment]
If you relaunch Sketch, does it work then?

**Comment by layeredges** [comment]
yes when i relaunch sketch it works, :)

**Comment by margusholland** [comment]
Ok. I’ve seen this happening myself, seems to be a bug in Sketch itself.

**Comment by layeredges** [comment]
ok got it, so should we report to sketch ?

**Comment by margusholland** [comment]
Would be nice if you could do it, if you manage to reproduce the actual steps to make it happen. I’ve seen it only once and there’s nothing in the console either that would make it easy to report it.

**Comment by layeredges** [comment]
okay
