### ISSUE TITLE
Sentence Case & Paragraph Breaks

### ISSUE THREAD

**Issue by smombartz** [margusholland/Comma#6]
Sentence case transformation doesn't start a new paragraph line with capitalized letter if previous line didn't end with a period (like in a list). It would be great if it could.

btw awesome plugin!

**Comment by margusholland** [comment]
Not sure what you mean by this. If I enter 2 separate lines with a line break in between, both lines get the same treatment, e.g. both get turned whatever case is activated. Can you maybe give me an example of the content you’re trying to convert.
