### ISSUE TITLE
Update for Sketch 3.8.1

### ISSUE THREAD

**Issue by ghost** [margusholland/Comma#7]
Hello. Some functions don't seem to work in Sketch 3.8.1. This plugin is really, really useful and I was hoping there might be an update soon?

Thanks!

**Comment by margusholland** [comment]
Thanks for the feedback. Seems that Sketch 3.8 has a bug and a method has been either accidentally or specifically removed. I’ve sent a bug report to Sketch about this, so hoping they’ll fix it soon.

**Comment by asyla** [comment]
Hi guys,

The plugin has stopped working in Sketch 3.8.2 (29753) as well. Need your help, please!
_Mac OS X El Capitan 10.11.4 (15E65)_

**Comment by margusholland** [comment]
We’re still waiting for news from Sketch. Nothing so far and 3.8.2 didn’t fix it either, I was hoping for this to be fixed.

**Comment by Nicodascorpio** [comment]
Hi, the plugin isn't working for me in 3.8.3. Has Sketch not addressed this bug yet? Really looking forward to using this plugin!

**Comment by margusholland** [comment]
No, unfortunately no news from Sketch on this so far.

**Comment by bomberstudios** [comment]
The method you were using was removed in 3.8 due to some refactoring and it's not coming back (will update the docs accordingly) so I sent you a pull request with a workaround.

Hope it helps, and sorry for the troubles!

**Comment by asyla** [comment]
Margus, thank you a lot! It's working fine now

**Comment by Nicodascorpio** [comment]
Confirmed! Works now! Thanks Margus!
